DROP TABLE IF EXISTS "Feedback" CASCADE;
DROP TABLE IF EXISTS "Weapon" CASCADE;
DROP TABLE IF EXISTS "BaseWeapon" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TYPE IF EXISTS "Role" CASCADE;
DROP TYPE IF EXISTS "FeedbackType" CASCADE;
DROP TYPE IF EXISTS "FeedbackStatus" CASCADE; 